# Generated by Django 5.0.4 on 2024-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ot', models.IntegerField()),
                ('num_ot', models.CharField(max_length=6)),
                ('ensamblaje', models.CharField(max_length=10)),
                ('componente', models.CharField(max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=11)),
                ('semana', models.CharField(max_length=40)),
                ('fec_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro cantidad',
                'verbose_name_plural': 'Registro cantidades',
                'db_table': 'tb_registro_cantidad_test',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
