# Generated by Django 5.0.4 on 2024-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoLineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.CharField(max_length=100, null=True)),
                ('linea', models.CharField(max_length=100)),
                ('nomenclatura_articulo', models.CharField(max_length=5)),
                ('ultimo_correlativo', models.IntegerField()),
                ('usuario_registro', models.CharField(max_length=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualiza', models.CharField(max_length=5, null=True)),
                ('fecha_actualiza', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Correlativo linea',
                'verbose_name_plural': 'Correlativo lineas',
                'db_table': 'tb_correlativo_lineas',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
